# Generated by Django 6.0.3 on 2026-03-17 02:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPagos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='pagos/')),
                ('formato', models.CharField(max_length=20)),
                ('total_registros', models.IntegerField(default=0)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('procesado', models.BooleanField(default=False)),
                ('procesado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
