# Generated by Django 6.0.3 on 2026-03-17 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_linea', models.IntegerField(default=0)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pagos.archivopagos')),
            ],
        ),
    ]
