# Generated by Django 6.0.3 on 2026-03-17 23:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoBancario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_certificado', models.CharField(max_length=100, unique=True)),
                ('banco', models.CharField(max_length=100)),
                ('cuenta_origen', models.CharField(max_length=100)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('autenticidad_verificada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
