# Generated by Django 6.0.3 on 2026-03-17 23:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoReconciliacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('tolerancia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_facturas', models.IntegerField(default=0)),
                ('facturas_conciliadas', models.IntegerField(default=0)),
                ('facturas_pendientes', models.IntegerField(default=0)),
                ('iniciado_at', models.DateTimeField(blank=True, null=True)),
                ('finalizado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
