# Generated by Django 6.0.3 on 2026-03-17 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
        ('conciliacion', '0001_initial'),
        ('facturas', '0001_initial'),
        ('pagos', '0002_registropago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coincidencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('EXACTA', 'Exacta'), ('PARCIAL', 'Parcial'), ('INCONSISTENTE', 'Inconsistente'), ('NO_ENCONTRADA', 'No encontrada')], default='NO_ENCONTRADA', max_length=20)),
                ('porcentaje_confianza', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificado_bancario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coincidencias', to='certificados.certificadobancario')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias', to='facturas.factura')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias', to='conciliacion.procesoreconciliacion')),
                ('registro_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coincidencias', to='pagos.registropago')),
            ],
        ),
    ]
